library(sensitivity)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(matrixStats)
library(miceadds)
#library(dtwclust)
library(vioplot)
library(xts)
#library(SWATplusR)
library(dplyr)
library(dygraphs)
library(ggplot2)
library(lubridate)
library(mapview)
library(plotly)
library(sf)
library(tibble)
library(tidyr)
library(purrr)
library(lhs)
library(hydroGOF)
library(forcats)
library(lubridate)
library(ggtext)
library(RColorBrewer)
library(cowplot)
library(zoo)
library(ggh4x)
library(pryr)
library(ps)
library(DT)
library(htmlwidgets)
library(webshot2)
library(ComplexHeatmap)
library(RColorBrewer)
#library(devtools)
#library(dplyr)
#library(dygraphs)
##library(fast) #error
#library(forcats)
#library(ggplot2)
#library(hydroGOF)
#library(lhs)
#library(lubridate)
#library(mapview)
#library(plotly)
#library(purrr)
#library(sensitivity)
#library(sf)
#library(tibble)
#library(tidyr)
#library(fitdistrplus)
#library(truncnorm)
#library(xts)
#require(data.table) # load it

## setup root directory path
if(Sys.info()[4]=="LZ26TPURUCKE-2"){
  # tom epa windows
  of_root <- file.path("c:", "Users", "tpurucke", "git", "wu_redcedar2")
}

data_in_dir <- file.path(of_root, "data_in")
data_out_dir <- file.path(of_root, "data_out")
graphics_dir <- file.path(of_root, "graphics")
src_dir <- file.path(of_root, "src")
hpc_data <- file.path(of_root, "hpc_data", "sim56-flux-weekly")
hpc_data_sensitivity <- file.path(of_root, "hpc_data", "sim56-sensitivity")

# For memory used by R
cat("Current R memory used: ", mem_used()/1e+9, "\n")
# Cross platform
m <- ps::ps_system_memory()
cat("Total RAM:", m$total/1E+9, "\n")
cat("Available RAM:", m$avail/1E+9, "\n")
gc()

# source other scripts
source(file.path(src_dir, "01load_hpc_data_local.R"))
source(file.path(src_dir, "02sensitivity_pcc.R"))
source(file.path(src_dir, "03kde_figure.R"))
source(file.path(src_dir, "04asims_time_series_daily.R"))
#source(file.path(src_dir, "04bsims_time_series_weekly.R"))
source(file.path(src_dir, "05aconditional_rainfall.R"))
source(file.path(src_dir, "05bconditional_rainfall_ma3.R"))
#source(file.path(src_dir, "06generation_mnse_boxplots.R"))
source(file.path(src_dir, "07final_manuscript_figures.R"))
